### PR TITLE
Force network recreation on cidr changing

### PR DESCRIPTION
**Pull request by fubbyb**

### CODE REVIEW

**Comment by fubbyb** [comment]
@LKaemmerling This PR related to our discussion in #127. Let's ask Terraform to remove and create this network resource for us.

**Comment by LKaemmerling** [comment]
This is not correct, not every change to the ip_range needs a force new creation of this. Even when you recreate the network all servers will need to be assigned to the new network and will get a new IP. So this behavior is fully that what we want. If you need to change the IP Range to another IP range instead of increasing the given range, you should simply delete the old network and create a new one.

**Comment by apricote** [comment]
Using [`CustomizeDiff`](https://www.terraform.io/docs/extend/resources/customizing-differences.html) and `customdiff.ForceNewIfChange`, it should be possible to check if the new `ip_range` is an extension/superset of the previous range, and only force the recreation if it is a completly different range.

**Comment by fubbyb** [comment]
The Go client implementation for HCloud doesn't have "ip_range" field in network update function. So currently you can not use a Customdiff.

When the client developers add this functionality, then it will be possible to return to the implementation of updating the "ip_range" attribute of the network resource.

In our company, we use Gitops flow, and now we had to solve this issue in two commits:
- remove the network resource
- add network resource with new cidr

Therefore, the downtime was a few minutes, not a few seconds.

**Comment by LKaemmerling** [comment]
@fubbyb The problem on this is that you didn't choose the correct private IP Range at the beginning. It is not possible to do this without the deleting of the network resource, because all servers need to be unassigned, then delete the network. This should be an explicit process because it changes the IP(s) from the servers too.

**Comment by vintury** [comment]
Hello.
I agree with @fubbyb - "If we cannot change the resource, then we can delete it and create a new one."

@LKaemmerling, you can detach network from hosts before remove?

I have big infrastructure.
Any error with the subnet mask will lead to manual intervention in the terraform database. This is unacceptable, as it can lead to complete inaccessibility of the infrastructure!

**Pull request closed without merging**
