### PR TITLE
Add initial 'hcloud_floating_ip_association' resource

### LINKED ISSUE #33: hcloud_floating_ip assign server_id after creation
I want to assign a  server_id to a hcloud_floating_ip instance after creation.

I first create "hcloud_floating_ip" without specifying an ip.
```
# master_ip/main.tf
terraform {
   backend "s3" {}
}

# Configure the Hetzner Cloud Provider
provider "hcloud" {
}

resource "hcloud_floating_ip" "master" {
  type = "ipv4"
  home_location = "fsn1"
  description = "agile-server"
  lifecycle {
    prevent_destroy = true
  }
}
```

Now I create a server, import the floating ip as remote state.

```
# server/main.tf
terraform {
   backend "s3" {}
}

# Configure the Hetzner Cloud Provider
provider "hcloud" {
}

resource "hcloud_server" "agile-prod" {
  name = "agile-prod"
  image = "ubuntu-16.04"
  server_type = "cx31"
  datacenter = "fsn1-dc8"
}



data "terraform_remote_state" "master" {
 backend = "s3"
 config {
  bucket = "agile-prod-terraform-state"
  key = "master_ip/terraform.tfstate"
  region = "eu-central-1"
  }
}
```

I add the floating ip to the server.
```
# server/main.tf
resource "null_resource" "add_ip" {
  connection {
      user        = "root"
      host        = "${hcloud_server.agile-prod.ipv4_address}"
      type        = "ssh"
  }

# add floating IP
  provisioner "remote-exec" {
    inline = [
     "sudo echo 'iface eth0 inet static\n address ${data.terraform_remote_state.master.floating_ip}/24\n' >> /etc/network/interfaces",
     "sudo ifdown eth0 && sudo ifup eth0",
    ]
  }
}
```

Now I still need to point the floating ip to the server but have no support for this operation.
I'll try to fix this with a manual api call as well https://github.com/hetznercloud/terraform-provider-hcloud/issues/32#issue-302080945 .

### PR DESCRIPTION
**Pull request by arminbuerkle**
Adds a `hcloud_floating_ip_association` resource which can be used to assign floating ips after server creation.

Resolves #33

### CODE REVIEW

**Comment by jjhbw** [comment]
Any idea when this will be merged? Really useful stuff. Same for #40.

**Comment by insekticid** [comment]
+1

**Comment by thetechnick** [comment]
This PR and #40 look really good.
I will come back to this after the technical review #41 is concluded.

**Comment by andir** [comment]
Any news on this?

**Comment by thetechnick** [comment]
We are in the final steps of the release process to become an officially supported terraform provider.
If everything works as planned we will release this week.

After the release I will work with @arminbuerkle to get this PR merged into the provider.

**Comment by thetechnick** [comment]
Can you please move this PR to the new repo?
https://github.com/terraform-providers/terraform-provider-hcloud

Then we can finally work on getting this merged!

**Pull request closed without merging**
