### PR TITLE
docs: add link to locations and datacenters docs

### PR DESCRIPTION
**Pull request by ghostdevv**
Adds links to the upstream Hetzner Docs to give more details about locations and datacenters.

### CODE REVIEW

**Comment by jooola** [comment]
Hey, 
I'd rather not have the datacenter list hard-coded in the documentation. The API provides datacenters as a dynamic resource, and we might forget to update the docs if a new location is added in the future.

Thanks for the proposal.

**Comment by ghostdevv** [comment]
@jooola there was already a list added to one of these pages in https://github.com/ghostdevv/terraform-provider-hcloud/commit/f2413a6edde0bb5f1b586ab6a7d5197f425ba429, but it was initially confusing to me why it was only in one place and what the `datacenter` string meant. Maybe it is worth an additional page that can be linked to that explains what it is, why it's different to the value of `location`, and what the current values are and how to get the latest ones. I had to go digging through issues to find the command, and I still don't completely understand what the difference in these two fields is.

**Comment by jooola** [comment]
@ghostdevv Hmm, I'll take a closer a look at this. Thanks for bringing this up.

**Comment by jooola** [comment]
@ghostdevv I published a list of available datacenters in the Hetzner Documentation, and added links to it to provide more details if needed.

This way we can safely update our docs once and not have to sync everything in the terraform docs.

Thanks for pushing to improve this!

**Review by jooola — APPROVED** [review]

**Comment by jooola** [comment]
Unrelated e2e tests are failing because the PR originates from a fork.

**Comment by ghostdevv** [comment]
Amazing, ty!

**Pull request merged**
