### PR TITLE
(enhancement):introduced sleep while starting the server in rescue mode

### PR DESCRIPTION
**Pull request by prabhatkumarthakur**
Most of the time while provisioning the server in rescue mode using terraform: the server fails to start right after provisioning.
Signed-off-by: prabhatkumarthakur <prabhat.thakur@mayadata.io>

### CODE REVIEW

**Comment by LKaemmerling** [comment]
Hey @prabhatkumarthakur,

in which location do you have this issue? We currently have a few problems with activating the rescue system directly after creating a server. It should be fixed in HEL.

**Comment by prabhatkumarthakur** [comment]
Hi @LKaemmerling 
Below is the server location.

*Server location:*

*City*: Helsinki
*Datacenter:* hel1-dc2
*Country: *Finland

**Comment by prabhatkumarthakur** [comment]
Hey @LKaemmerling 
Today also I hit the above issue couple of times
Screenshot from 2021-05-05 19-35-58

**Comment by LKaemmerling** [comment]
@prabhatkumarthakur can You provide us an ID of the server? This would help us debugging the problem.

**Comment by prabhatkumarthakur** [comment]
@LKaemmerling  The server id is 
#11700790
Screenshot from 2021-05-06 20-30-46

**Comment by LKaemmerling** [comment]
Hey @prabhatkumarthakur,

thank you! I passed it to the colleagues. On the first view it doesn't look like it is related to the Terraform provider. One question, when you try to start this server, does this work?

**Comment by prabhatkumarthakur** [comment]
Hi @LKaemmerling 
Yes, the server works once I power it on.

**Comment by arne-rusek** [comment]
> Hey @prabhatkumarthakur,
> 
> thank you! I passed it to the colleagues. On the first view it doesn't look like it is related to the Terraform provider. One question, when you try to start this server, does this work?

Hi @LKaemmerling. I'm colleague of @prabhatkumarthakur. I'm pretty sure it isn't related to terraform provider at all and that the issue is somehow in the infra and maybe specifically the process we use. Never happened to me when creating VMs from official image, just when booting to rescue from snapshot-provisioned VM. In the last days it got a lot better. When I started (~week ago) 

it was like 30%+ failure rate, yesterday it was 2 servers out of ~30 created. The patch however does retry (after waiting a bit) which works around the issue. When I start the server manually it works, however terraform script will exit with error and that fails our CI/CD jobs. It would of course be nicer if it always worked on the first try.

2021-04-29_171258 40_sshot(1)

**Comment by prabhatkumarthakur** [comment]
Hey @LKaemmerling 
Any update on this?

**Comment by LKaemmerling** [comment]
Hey @prabhatkumarthakur,

sorry, I was on vacation. I will ask our team about the current state and then come back to you.

**Comment by prabhatkumarthakur** [comment]
@LKaemmerling 
Can you please update me on this?

**Comment by LKaemmerling** [comment]
Hey @prabhatkumarthakur,

based on the replies of our team there shouldn't be a problem anymore. Can you retest it?

**Comment by prabhatkumarthakur** [comment]
Thanks @LKaemmerling 
I will let you know if the same issue is hit again.

**Comment by mysticaltech** [comment]
We are experiencing the same with our [kube-hetzner ](https://github.com/kube-hetzner/kube-hetzner) project. Many times, the server starts `off`. And have opened a similar issue here https://github.com/hetznercloud/terraform-provider-hcloud/issues/505.

**Comment by mysticaltech** [comment]
@prabhatkumarthakur Your proposed changes allow us to successfully bypass this issue correct? Am thinking of forking and implementing the same fix myself, because this problem has become really huge for us, as we make heavy use of the rescue mode.

**Comment by mysticaltech** [comment]
@prabhatkumarthakur Did that bug disappear for you, or are you just using the changes proposed in this PR to mitigate it?

**Comment by mysticaltech** [comment]
@LKaemmerling Until this bug gets fixed for good on your platform, why not just **merge that PR**, it's a simple retry that cannot do any harm, on the contrary, it's a nice measure that would make many of us love using Hetzner terraform even more.

It does the exact same procedure that we do manually now to make it work. Almost 60% of our deployments are failing because of that issue. We have to `hcloud server poweron node-name` and `terraform apply` again... Such a loss of time and so frustrating.

This PR only adds some much-needed resiliency to the delicate setRescue operation - But definitely, it is great to address the root cause of the issue too.

**Comment by LKaemmerling** [comment]
Superseeded by #511

**Pull request closed without merging**
