### PR TITLE
#399 apply to for firewall resource

### PR DESCRIPTION
**Pull request by ilavsky-healthinel**
Implemented argument 'apply_to' for resource 'firewall'. Thanks to this there is finally a way to apply firewall also to 'labelSelector' rather to only set it to specific server id's.

### CODE REVIEW

**Comment by serverfriendsorg** [comment]
Is there already a ETA when this feature will be merged?

**Comment by FriesPascal** [comment]
Also hoping for a merge since this would solve #336

**Comment by ghost** [comment]
@LKaemmerling would you mind to review the PR?

**Comment by LKaemmerling** [comment]
Hey @ilavsky-healthinel,

thank you for your MR. I submitted my own MR that also includes tests and the possibility to update the firewall without the need to force create it. Thank you again for the work you did here.

MR from our side: https://github.com/hetznercloud/terraform-provider-hcloud/pull/450

**Comment by ilavsky-healthinel** [comment]
> Hey @ilavsky-healthinel,
> 
> thank you for your MR. I submitted my own MR that also includes tests and the possibility to update the firewall without the need to force create it. Thank you again for the work you did here.
> 
> MR from our side: #450

Hey @LKaemmerling,

no worries, did it because I needed it, and then I thought of contributing so I'm glad it helped. Now I can switch fully to the official hcloud provider, thx!

**Pull request closed without merging**
