### PR TITLE
feat(server): add `primary_disk_size` attribute in resource and datasource

### PR DESCRIPTION
**Pull request by EttoreFoti**
Resolve enhancement request in issue #683.

### CODE REVIEW

**Comment by EttoreFoti** [comment]
Integrations test failing because it looks like a repo secret is missing.

**Review by apricote — CHANGES_REQUESTED** [review]
Very nice!

Could you add the new attribute to the docs pages?

- https://github.com/hetznercloud/terraform-provider-hcloud/blob/fa7ea1f167750e64cc9ebbb26ce0eb8171d55df6/website/docs/r/server.html.md?plain=1#L192
- https://github.com/hetznercloud/terraform-provider-hcloud/blob/fa7ea1f167750e64cc9ebbb26ce0eb8171d55df6/website/docs/d/server.html.md?plain=1#L31

**Comment by apricote** [comment]
Integration tests are expected to fail. GitHub makes it very hard to allow access to Secrets to external contributors. We are working on an alternative solution :)

**Comment by EttoreFoti** [comment]
Changes added, thanks for the explanation :)

**Review by apricote — APPROVED** [review]
I pushed another commit to move the attribute to the right section, it was previously in the explanation of the `network` block.

Thanks a lot for the new feature @EttoreFoti!

**Pull request merged**
